title: Axolotl # The top-level website title
description: The story of an adorable aquatic creature # A tagline that usually appears in your site header

remote_theme: pages-themes/cayman@v0.2.0 # Establishes a theme
plugins:
- jekyll-remote-theme
